/**
 * Standard Genuine Spare Parts Catalog for Sheriyakam Technicians
 * Covers 14 Kerala districts with standard wholesale tariffs, BIS/ISI certifications, and HSN codes.
 */

export const PARTS_CATEGORIES = [
    { id: 'all', label: 'All Spares' },
    { id: 'electrical', label: 'Electrical & Switchgear' },
    { id: 'ac', label: 'AC & Cooling' },
    { id: 'wiring', label: 'Cables & Conduits' },
    { id: 'cctv_plumbing', label: 'CCTV & Accessories' },
];

export const PARTS_CATALOG = [
    // Electrical & Switchgear (HSN 8536)
    {
        id: 'part-mcb-16a',
        sku: 'HAV-MCB-16-C',
        name: 'Havells 16A Single Pole C-Curve MCB',
        category: 'electrical',
        manufacturer: 'Havells India Ltd.',
        isiMark: 'IS/IEC 60898-1',
        hsn: '85362030',
        unit: 'piece',
        rate: 190,
        gstRate: 0.18,
        description: 'Standard 10kA breaking capacity for residential light & fan circuits',
        inStock: true,
    },
    {
        id: 'part-mcb-32a',
        sku: 'HAV-MCB-32-C',
        name: 'Havells 32A Single Pole C-Curve MCB',
        category: 'electrical',
        manufacturer: 'Havells India Ltd.',
        isiMark: 'IS/IEC 60898-1',
        hsn: '85362030',
        unit: 'piece',
        rate: 220,
        gstRate: 0.18,
        description: 'Heavy-duty 10kA MCB for geysers, 1.5-ton ACs, and kitchen circuits',
        inStock: true,
    },
    {
        id: 'part-rccb-40a',
        sku: 'SCH-RCCB-40-30',
        name: 'Schneider 40A 2-Pole 30mA RCCB / ELCB',
        category: 'electrical',
        manufacturer: 'Schneider Electric India',
        isiMark: 'IS 12640-1',
        hsn: '85362020',
        unit: 'piece',
        rate: 1850,
        gstRate: 0.18,
        description: 'Human electric shock & earth leakage protection (Mandatory Kerala KSEB rule)',
        inStock: true,
    },
    {
        id: 'part-switch-6a',
        sku: 'ANC-ROMA-6A-SW',
        name: 'Anchor Roma 6A 1-Way Modular Switch',
        category: 'electrical',
        manufacturer: 'Panasonic Life Solutions India',
        isiMark: 'IS 3854',
        hsn: '85365020',
        unit: 'piece',
        rate: 45,
        gstRate: 0.18,
        description: 'Classic White fire-retardant polycarbonate modular switch',
        inStock: true,
    },
    {
        id: 'part-socket-16a',
        sku: 'ANC-ROMA-16A-SK',
        name: 'Anchor Roma 16A 3-Pin Power Socket with Safety Shutter',
        category: 'electrical',
        manufacturer: 'Panasonic Life Solutions India',
        isiMark: 'IS 1293',
        hsn: '85366910',
        unit: 'piece',
        rate: 140,
        gstRate: 0.18,
        description: 'Child safety shuttered socket for microwave, fridge, and iron',
        inStock: true,
    },
    {
        id: 'part-cap-fan',
        sku: 'ANC-CAP-25UF',
        name: 'Anchor 2.5 µF Ceiling Fan Run Capacitor',
        category: 'electrical',
        manufacturer: 'Panasonic Life Solutions India',
        isiMark: 'IS 1709',
        hsn: '85322500',
        unit: 'piece',
        rate: 85,
        gstRate: 0.18,
        description: 'Oil-filled metallized polypropylene capacitor for slow-running fans',
        inStock: true,
    },

    // Wiring & Conduits (HSN 8544)
    {
        id: 'part-wire-15',
        sku: 'FIN-FR-15-MTR',
        name: 'Finolex 1.5 sq mm FRLS Copper Wire (Per 5 Metres)',
        category: 'wiring',
        manufacturer: 'Finolex Cables Ltd.',
        isiMark: 'IS 694',
        hsn: '85444999',
        unit: '5m coil',
        rate: 180,
        gstRate: 0.18,
        description: 'Flame retardant low smoke 100% electrolytic bare copper',
        inStock: true,
    },
    {
        id: 'part-wire-25',
        sku: 'FIN-FR-25-MTR',
        name: 'Finolex 2.5 sq mm FRLS Copper Wire (Per 5 Metres)',
        category: 'wiring',
        manufacturer: 'Finolex Cables Ltd.',
        isiMark: 'IS 694',
        hsn: '85444999',
        unit: '5m coil',
        rate: 290,
        gstRate: 0.18,
        description: 'Power circuit wiring for ACs, geysers, and distribution mains',
        inStock: true,
    },
    {
        id: 'part-ins-tape',
        sku: 'STL-TAPE-PVC',
        name: 'Steelgrip / Anchor PVC Electrical Insulation Tape (Set of 2)',
        category: 'wiring',
        manufacturer: 'Anchor / Pidilite Ltd.',
        isiMark: 'IS 7809',
        hsn: '39191000',
        unit: 'pack of 2',
        rate: 35,
        gstRate: 0.18,
        description: 'High adhesion moisture & voltage resistant wire insulation tape',
        inStock: true,
    },

    // AC & Cooling (HSN 8415 / 8532)
    {
        id: 'part-ac-cap-45',
        sku: 'EPCOS-45UF-AC',
        name: 'Epcos/TDK 45+5 µF Dual Run AC Compressor Capacitor',
        category: 'ac',
        manufacturer: 'TDK India Electronics',
        isiMark: 'IS 2993',
        hsn: '85322500',
        unit: 'piece',
        rate: 380,
        gstRate: 0.18,
        description: 'Heavy duty capacitor for 1.5T / 2.0T split AC compressor and outdoor fan',
        inStock: true,
    },
    {
        id: 'part-ac-drain-pipe',
        sku: 'AIR-DRN-PIPE-2M',
        name: 'Reinforced Flexible AC Condensate Drain Pipe (3 Metres)',
        category: 'ac',
        manufacturer: 'Supreme Industries',
        isiMark: 'IS 4985',
        hsn: '39172190',
        unit: '3m pipe',
        rate: 120,
        gstRate: 0.18,
        description: 'UV-stabilized anti-clog drain hose prevents indoor AC water leakage',
        inStock: true,
    },
    {
        id: 'part-ac-flare-nuts',
        sku: 'COP-FLR-NUT-SET',
        name: 'Brass Flare Nut & Copper Coupling Set (1/4" & 1/2")',
        category: 'ac',
        manufacturer: 'Mandev Tubes India',
        isiMark: 'ASTM B280',
        hsn: '74122000',
        unit: 'set',
        rate: 260,
        gstRate: 0.18,
        description: 'High-pressure brass refrigeration nuts for R32/R410A gas lines',
        inStock: true,
    },

    // CCTV & Smart Home (HSN 8504 / 8529)
    {
        id: 'part-cctv-adapter',
        sku: 'CP-PWR-12V2A',
        name: 'CP Plus 12V 2A Regulated CCTV Power Adapter',
        category: 'cctv_plumbing',
        manufacturer: 'CP Plus India',
        isiMark: 'IS 13252',
        hsn: '85044090',
        unit: 'piece',
        rate: 320,
        gstRate: 0.18,
        description: 'Surge protected SMPS power supply with copper BNC connector cable',
        inStock: true,
    },
    {
        id: 'part-bnc-dc-pack',
        sku: 'HIK-BNC-DC-SET',
        name: 'Copper BNC Video Balun & DC Pin Connectors (Pair)',
        category: 'cctv_plumbing',
        manufacturer: 'Hikvision / Prama India',
        isiMark: 'IEC 61169',
        hsn: '85299090',
        unit: 'pair',
        rate: 90,
        gstRate: 0.18,
        description: 'Lossless coaxial video and 12V power terminal connectors',
        inStock: true,
    }
];

export const getPartsByCategory = (category = 'all') => {
    if (category === 'all') return PARTS_CATALOG;
    return PARTS_CATALOG.filter(p => p.category === category);
};

export const getPartById = (id) => {
    return PARTS_CATALOG.find(p => p.id === id) || null;
};
